import { Aleo } from "next/font/google";
import "./globals.css";
import HeaderComponent from "../src/components/Header/HeaderComponent";
import FooterComponent from "../src/components/Footer/FooterComponent";

const aleo = Aleo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={aleo.className}>

        <HeaderComponent title={`🔥 Fireplace Palace`}/>
             {children}
         <FooterComponent />

     </body>
</html>
  );
}
